version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      app_network:
        ipv4_address: 172.20.0.2

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mongodb
    ports:
      - "3000:3000"  # Make sure this is uncommented and active
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mydatabase
    networks:
      app_network:
        ipv4_address: 172.20.0.3

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:5173"
    environment:
      - VITE_API_URL=http://backend:3000
    networks:
      app_network:
        ipv4_address: 172.20.0.4

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  mongo_data: